from __future__ import annotations

MIN_CONFIDENCE = 0.65
MIN_TRANSFER = 0.60
MAX_EPISODES_TO_STABLE = 5
COOLDOWN_CYCLES = 3
MAX_INTERNAL_GOALS_PER_LOOP = 1
MAX_CURRICULUM_ITEMS = 3
SELF_IMPROVEMENT_BUDGET_STEPS = 3
